// src/components/ProjectCard.vue
<template>
  <div class="card">
    <router-link :to="`/work/${name}`">
      <img :src="`/images/projects/${image}`" :alt="name">
    </router-link>
    <div class="card__description">{{ description }}</div>
    <router-link :to="`/work/${name}`">{{ link }}</router-link>
  </div>
</template>

<script>
export default {
  props: {
    image: {
      type: String,
      required: true,
    },
    name: {
      type: String,
      required: true,
    },
    description: {
      type: String,
      required: true,
    },
    link: {
      type: String,
      required: true,
    },
  },
};
</script>

<style lang="stylus">
.card
  margin-bottom 30px
  font-size 15px

  &__description
    font-family $FONT_SECOND
    margin 10px 0 5px
</style>

// src/app/components/project-card/project-card.component.ts
import { Component, Input } from '@angular/core';
import { RouterLink } from '@angular/router';

@Component({
  selector: 'app-project-card',
  standalone: true,
  imports: [RouterLink],
  templateUrl: './project-card.component.html',
  styleUrl: './project-card.component.scss',
})
export class ProjectCardComponent {
  @Input({ required: true }) image: string;
  @Input({ required: true }) name: string;
  @Input({ required: true }) description: string;
  @Input({ required: true }) link: string;
}

<div class="card">
  <a [routerLink]="'/work/' + name">
    <img [src]="'/assets/images/projects/' + image" [alt]="name" />
  </a>
  <div class="card__description">{{ description }}</div>
  <a [routerLink]="'/work/' + name">{{ link }}</a>
</div>
